;
;    This file was generated by the GEOS Resource Compiler
;
;    DO NOT EDIT! Any changes will be lost!
;
;    Edit proper resource file instead.
;

    .import __BSS_SIZE__, __STARTUP_RUN__
    .import __VLIR0_START__, __VLIR0_LAST__
    .import __VLIR0_BLOCKS__
    .import __VLIR1_BLOCKS__
    .import __VLIR2_BLOCKS__
    .import __VLIR3_BLOCKS__
    .import __VLIR4_BLOCKS__
    .import __VLIR5_BLOCKS__
    .import __VLIR6_BLOCKS__
    .import __VLIR7_BLOCKS__
    .import __VLIR8_BLOCKS__
    .import __VLIR9_BLOCKS__
    .import __VLIR10_BLOCKS__
    .import __VLIR11_BLOCKS__
    .import __VLIR12_BLOCKS__
    .import __VLIR13_BLOCKS__
    .import __VLIR14_BLOCKS__
    .import __VLIR15_BLOCKS__
    .import __VLIR16_BLOCKS__
    .import __VLIR17_BLOCKS__
    .import __VLIR18_BLOCKS__
    .import __VLIR19_BLOCKS__

    .segment "DIRENTRY"

    .byte 130
    .word 0
    .byte "eyes"
    .res  (16 - 4), $a0
    .word 0
    .byte 0
    .byte 6
    .byte 26, 6, 16, 8, 41

    .word 1 + __VLIR0_BLOCKS__ + __VLIR1_BLOCKS__ + __VLIR2_BLOCKS__ + __VLIR3_BLOCKS__ + __VLIR4_BLOCKS__ + __VLIR5_BLOCKS__ + __VLIR6_BLOCKS__ + __VLIR7_BLOCKS__ + __VLIR8_BLOCKS__ + __VLIR9_BLOCKS__ + __VLIR10_BLOCKS__ + __VLIR11_BLOCKS__ + __VLIR12_BLOCKS__ + __VLIR13_BLOCKS__ + __VLIR14_BLOCKS__ + __VLIR15_BLOCKS__ + __VLIR16_BLOCKS__ + __VLIR17_BLOCKS__ + __VLIR18_BLOCKS__ + __VLIR19_BLOCKS__
    .byte "SEQ formatted GEOS file V1.0"

    .segment "FILEINFO"

    .byte 3, 21, 63 | $80
    .byte %11111111, %11111111, %11111111
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %10000000, %00000000, %00000001
    .byte %11111111, %11111111, %11111111
    .byte 130, 6, 0
    .word __VLIR0_START__, __VLIR0_START__ - 1, __STARTUP_RUN__

    .byte "geoEyes"
    .res  (12 - 7), $20
    .byte "V1.0"
    .byte 0, 0, 0
    .byte 0

    .byte "Stefan Haubenthal"
    .byte 0
    .res  (63 - 18)

    .byte "The famous follow the mouse demo."
    .byte 0

