;
; File generated by cc65 v 2.19 - Git cc3c40c54
;
	.fopt		compiler,"cc65 v 2.19 - Git cc3c40c54"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_Sleep
	.import		_HorizontalLine
	.import		_StartMouseMode
	.import		_ClearMouseMode
	.import		_DrawSprite
	.import		_PosSprite
	.import		_EnablSprite
	.import		_DisablSprite
	.import		_FirstInit
	.import		_InitForIO
	.import		_EnterDeskTop
	.export		_main

.segment	"RODATA"

_pupil:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$05
	.byte	$55
	.byte	$40
	.byte	$57
	.byte	$FF
	.byte	$54
	.byte	$5F
	.byte	$FF
	.byte	$D4
	.byte	$57
	.byte	$FF
	.byte	$54
	.byte	$05
	.byte	$55
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_eye_span:
	.byte	$00
	.byte	$06
	.byte	$09
	.byte	$0B
	.byte	$0C
	.byte	$0E
	.byte	$0F
	.byte	$10
	.byte	$11
	.byte	$12
	.byte	$13
	.byte	$13
	.byte	$14
	.byte	$15
	.byte	$15
	.byte	$16
	.byte	$16
	.byte	$17
	.byte	$17
	.byte	$17
	.byte	$18
	.byte	$18
	.byte	$18
	.byte	$18
	.byte	$18
	.byte	$19
	.byte	$19
	.byte	$19
	.byte	$19
	.byte	$19
	.byte	$19

; ---------------------------------------------------------------
; unsigned int __near__ isqrt (unsigned int n)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_isqrt: near

.segment	"CODE"

	jsr     pushax
	jsr     push0
	jmp     L0004
L0002:	ldx     #$00
	lda     #$01
	jsr     addeq0sp
L0004:	jsr     pushw0sp
	ldy     #$03
	jsr     ldaxysp
	jsr     tosumulax
	ldy     #$02
	cmp     (c_sp),y
	txa
	iny
	sbc     (c_sp),y
	bcc     L0002
	jsr     pushw0sp
	ldy     #$03
	jsr     ldaxysp
	jsr     tosumulax
	sec
	ldy     #$02
	sbc     (c_sp),y
	sta     tmp1
	txa
	iny
	sbc     (c_sp),y
	ora     tmp1
	bcc     L0005
	beq     L0005
	ldx     #$00
	lda     #$01
	jsr     subeq0sp
L0005:	jsr     ldax0sp
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ draw_eye (unsigned int cx, char cy)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_eye: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	lda     #$E2
	ldy     #$00
	sta     (c_sp),y
	ldx     #$00
L0013:	lda     (c_sp),y
	bpl     L0006
	dex
L0006:	cmp     #$1F
	txa
	sbc     #$00
	bvc     L0007
	eor     #$80
L0007:	jpl     L0003
	lda     #$1E
	jsr     pusha0
	ldy     #$02
	lda     (c_sp),y
	asl     a
	bcc     L0015
	lda     (c_sp),y
	bpl     L000B
	ldx     #$FF
L000B:	jsr     negax
	jmp     L000D
L0015:	lda     (c_sp),y
	bpl     L000D
	ldx     #$FF
L000D:	jsr     tossubax
	jsr     pushax
	jsr     ldax0sp
	sta     ptr1
	txa
	clc
	adc     #>(_eye_span)
	sta     ptr1+1
	ldy     #<(_eye_span)
	lda     (ptr1),y
	jsr     pusha0
	lda     (c_sp,x)
	ldy     #$01
	ora     (c_sp),y
	beq     L000E
	tya
	jsr     pusha
	ldy     #$05
	lda     (c_sp),y
	clc
	iny
	adc     (c_sp),y
	jsr     pusha
	ldy     #$09
	jsr     ldaxysp
	sec
	ldy     #$02
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	clc
	ldy     #$0A
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     _HorizontalLine
L000E:	jsr     incsp4
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
	jpl     L0013
	jmp     L0013
L0003:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ get_pupil_pos (int mx, int my, int ex, int ey, int *px, int *py)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_get_pupil_pos: near

.segment	"CODE"

	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	sec
	ldy     #$06
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	sec
	ldy     #$06
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	cpx     #$80
	bcc     L0002
	ldy     #$03
	jsr     ldaxysp
	jsr     negax
	jmp     L0003
L0002:	ldy     #$03
	jsr     ldaxysp
L0003:	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	cpx     #$80
	bcc     L0004
	ldy     #$03
	jsr     ldaxysp
	jsr     negax
	jmp     L0005
L0004:	ldy     #$03
	jsr     ldaxysp
L0005:	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	ldy     #$05
	jsr     ldaxysp
	jsr     tosumulax
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	ldy     #$05
	jsr     ldaxysp
	jsr     tosumulax
	jsr     tosaddax
	jsr     _isqrt
	jsr     pushax
	jsr     ldax0sp
	cmp     #$0D
	txa
	sbc     #$00
	bvs     L0007
	eor     #$80
L0007:	bpl     L0006
	jsr     ldax0sp
	cmp     #$01
	txa
	sbc     #$00
	bvs     L0009
	eor     #$80
L0009:	bpl     L0006
	ldy     #$0B
	jsr     pushwysp
	lda     #$0C
	jsr     tosmula0
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosdivax
	ldy     #$08
	jsr     staxysp
	ldy     #$09
	jsr     pushwysp
	lda     #$0C
	jsr     tosmula0
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosdivax
	ldy     #$06
	jsr     staxysp
L0006:	ldy     #$0D
	jsr     ldptr1ysp
	ldy     #$09
	jsr     ldaxysp
	clc
	ldy     #$10
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	ldy     #$0B
	jsr     ldptr1ysp
	ldy     #$07
	jsr     ldaxysp
	clc
	ldy     #$0E
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	ldy     #$16
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp6
	jsr     _FirstInit
	jsr     _InitForIO
	lda     #$01
	jsr     pusha
	lda     #<(_pupil)
	ldx     #>(_pupil)
	jsr     _DrawSprite
	lda     #$02
	jsr     pusha
	lda     #<(_pupil)
	ldx     #>(_pupil)
	jsr     _DrawSprite
	lda     $D017
	ora     #$06
	sta     $D017
	lda     #$01
	sta     $D025
	lda     #$0B
	sta     $D026
	lda     #$00
	sta     $D028
	sta     $D029
	lda     $D01C
	ora     #$06
	sta     $D01C
	lda     #$4B
	jsr     pusha0
	lda     #$5A
	jsr     _draw_eye
	lda     #$E1
	jsr     pusha0
	lda     #$5A
	jsr     _draw_eye
	lda     #$01
	jsr     _EnablSprite
	lda     #$02
	jsr     _EnablSprite
	jsr     _StartMouseMode
	jmp     L0004
L0002:	lda     $003A
	ldx     $003A+1
	jsr     pushax
	lda     $003C
	jsr     pusha0
	jsr     decsp4
	ldy     #$09
	jsr     pushwysp
	ldy     #$09
	jsr     pushwysp
	lda     #$4B
	jsr     pusha0
	lda     #$5A
	jsr     pusha0
	lda     #$0A
	jsr     leaa0sp
	jsr     pushax
	lda     #$0A
	jsr     leaa0sp
	jsr     _get_pupil_pos
	ldy     #$03
	jsr     ldaxysp
	cmp     #$0D
	txa
	sbc     #$00
	bvs     L0005
	eor     #$80
L0005:	asl     a
	lda     #$00
	tax
	bcc     L0007
	ldy     #$03
	jsr     ldaxysp
	ldy     #$0C
	jsr     decaxy
L0007:	ldy     #$0B
	jsr     staxysp
	jsr     ldax0sp
	cmp     #$0B
	txa
	sbc     #$00
	bvs     L0008
	eor     #$80
L0008:	asl     a
	lda     #$00
	bcc     L0013
	jsr     ldax0sp
	ldy     #$0A
	jsr     decaxy
L0013:	ldy     #$0D
	sta     (c_sp),y
	lda     #$01
	jsr     pusha
	lda     #$0C
	jsr     leaa0sp
	jsr     _PosSprite
	ldy     #$09
	jsr     pushwysp
	ldy     #$09
	jsr     pushwysp
	lda     #$E1
	jsr     pusha0
	lda     #$5A
	jsr     pusha0
	lda     #$0A
	jsr     leaa0sp
	jsr     pushax
	lda     #$0A
	jsr     leaa0sp
	jsr     _get_pupil_pos
	ldy     #$03
	jsr     ldaxysp
	cmp     #$0D
	txa
	sbc     #$00
	bvs     L000B
	eor     #$80
L000B:	asl     a
	lda     #$00
	tax
	bcc     L000D
	ldy     #$03
	jsr     ldaxysp
	ldy     #$0C
	jsr     decaxy
L000D:	ldy     #$08
	jsr     staxysp
	jsr     ldax0sp
	cmp     #$0B
	txa
	sbc     #$00
	bvs     L000E
	eor     #$80
L000E:	asl     a
	lda     #$00
	bcc     L0016
	jsr     ldax0sp
	ldy     #$0A
	jsr     decaxy
	jmp     L0017
L0016:	ldy     #$0A
L0017:	sta     (c_sp),y
	lda     #$02
	jsr     pusha
	lda     #$09
	jsr     leaa0sp
	jsr     _PosSprite
	ldx     #$00
	lda     #$01
	jsr     _Sleep
	jsr     incsp8
L0004:	lda     $0039
	and     #$80
	jeq     L0002
	lda     #$01
	jsr     _DisablSprite
	lda     #$02
	jsr     _DisablSprite
	jsr     _ClearMouseMode
	jsr     _EnterDeskTop
	ldx     #$00
	txa
	rts

.endproc

